spring:
  dubbo:
    server: false
    application:
      name: provider
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880

server:
  port: 8080